# Generated by Django 5.2.8 on 2025-11-20 03:11

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo Evento')),
                ('fecha_evento', models.DateField(verbose_name='Fecha Evento')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar Evento')),
                ('descripcion', models.TextField(verbose_name='Descripcion Evento')),
                ('publicado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['id'],
            },
        ),
    ]
