# Generated by Django 5.2.8 on 2025-11-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateTimeField(verbose_name='Fecha Evento'),
        ),
    ]
