# Generated by Django 5.2.8 on 2025-11-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.CharField(choices=[('1', 'Antioquia')], max_length=1, verbose_name='Departamento'),
        ),
    ]
