# Generated by Django 5.2.8 on 2025-11-21 13:06

import ckeditor_uploader.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripcion')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipo/', verbose_name='Foto')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Persona del Equipo',
                'verbose_name_plural': 'Personas del Equipo',
                'ordering': ['cargo', 'nombre'],
            },
        ),
    ]
