# Generated by Django 5.2.8 on 2025-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
