# Generated by Django 5.2.8 on 2025-12-04 20:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0002_alter_equipo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
