# Generated by Django 5.2.8 on 2025-11-20 23:24

import ckeditor_uploader.fields
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('mensaje', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('leido', models.BooleanField(default=False, verbose_name='Mensaje Leido')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contato',
                'ordering': ['fecha'],
            },
        ),
    ]
