# Generated by Django 5.2.8 on 2025-11-19 22:55

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('municipios', '0002_alter_municipio_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo Visita')),
                ('fecha_visita', models.DateField(verbose_name='Fecha Visita')),
                ('resumen', models.TextField(verbose_name='Resumen')),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Contenido')),
                ('imagen_principal', models.ImageField(upload_to='visitas/', verbose_name='Imagen Principal')),
                ('fecha_publicado', models.DateField(verbose_name='Fecha Publicacion')),
                ('publicado', models.BooleanField(default=False)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_visita', to='municipios.municipio')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FotoVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('imagen', models.ImageField(upload_to='visitas/galeria/', verbose_name='Imagen')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotovisita_visita', to='visitas.visita')),
            ],
            options={
                'verbose_name': 'Foto Visita',
                'verbose_name_plural': 'Fotos Visitas',
                'ordering': ['id'],
            },
        ),
    ]
