# Generated by Django 5.2.8 on 2025-12-04 21:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_alter_visita_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotovisita',
            name='imagen',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='imagen_principal',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen'),
        ),
    ]
